name: CI

on:
  push:
    tags:    [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake + Ninja
        uses: lukka/get-cmake@v3.30.3

      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build pkg-config \
            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxext-dev libxi-dev \
            libgl1-mesa-dev libudev-dev \
            libopenal-dev libflac-dev libvorbis-dev libogg-dev \
            libdrm-dev libgbm-dev libwayland-dev wayland-protocols \
            libfreetype6-dev

      - name: Configure
        run: >
          cmake -S . -B build
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Install (stage)
        run: cmake --install build --config Release --prefix "dist/${{ runner.os }}"

      # Удаляем лишнее: include SFML и cmake-скрипты
      - name: Remove unnecessary SFML files (Linux)
        if: runner.os == 'Linux'
        run: |
          rm -rf "dist/${{ runner.os }}/include" \
                 "dist/${{ runner.os }}/lib/cmake"

      - name: Remove unnecessary SFML files (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force "dist/Windows/include"
          Remove-Item -Recurse -Force "dist/Windows/lib/cmake"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HeartStringsFunnyBones-${{ runner.os }}
          path: dist/${{ runner.os }}/

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: HeartStringsFunnyBones-windows-latest
          path: dist/Windows

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: HeartStringsFunnyBones-ubuntu-latest
          path: dist/Linux

      - name: Pack Windows
        run: |
          cd dist
          zip -r HeartStringsFunnyBones-Windows.zip Windows
      - name: Pack Linux
        run: |
          cd dist
          tar -czf HeartStringsFunnyBones-Linux.tar.gz Linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/HeartStringsFunnyBones-Windows.zip
            dist/HeartStringsFunnyBones-Linux.tar.gz
          draft: false
          prerelease: false
