name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CMake + Ninja
        uses: lukka/get-cmake@v3.30.3

      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build pkg-config \
            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxext-dev \
            libgl1-mesa-dev libudev-dev \
            libopenal-dev libflac-dev libvorbis-dev libogg-dev \
            libdrm-dev libgbm-dev libwayland-dev wayland-protocols \
            libfreetype6-dev

      - name: Configure
        run: >
          cmake -S . -B build
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DBUNDLE_SFML=ON
          -DBUNDLE_JSON=ON

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Install (stage)
        run: cmake --install build --config Release --prefix "dist/${{ runner.os }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HeartStringsFunnyBones-${{ runner.os }}
          path: dist/${{ runner.os }}
